"""
Document Metadata repository — all database operations for the document_metadata table.

Key operations:
  - create():      Called by the upload endpoint after a successful MinIO PUT.
  - get_by_doc_id: Used by GET /documents/{doc_id} to fetch a single record.
  - get_by_nis_id: Used by GET /nis/{nis_id}/documents to list all docs for a person.
  - soft_delete(): Sets is_deleted=True, records deleted_at timestamp.
                   Does NOT remove from database — preserves audit trail.

Soft-delete pattern:
  All list queries filter is_deleted=False by default.
  Pass include_deleted=True to include soft-deleted rows (e.g. audit endpoints).
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Optional

from sqlalchemy.orm import Session

from app.models.document_metadata import DocumentMetadata


class DocumentMetadataRepository:
    def __init__(self, db: Session) -> None:
        self._db = db

    # ── Writes ────────────────────────────────────────────────────────────────

    def create(
        self,
        doc_id:                str,
        nis_id:                str,
        file_name:             str,
        document_type:         str,
        document_class:        str,
        bucket_name:           str,
        object_path:           str,
        content_type:          Optional[str]  = None,
        file_size_bytes:       Optional[int]  = None,
        uploaded_by:           Optional[str]  = None,
        correlation_id:        Optional[str]  = None,
        salesforce_record_id:  Optional[str]  = None,
        salesforce_object_type: Optional[str] = None,
        description:           Optional[str]  = None,
        expiry_date:           Optional[str]  = None,
        etag:                  Optional[str]  = None,
        version_id:            Optional[str]  = None,
    ) -> DocumentMetadata:
        """
        Insert a document_metadata row after a successful MinIO upload.
        doc_id must be unique (generated by the service layer).
        """
        record = DocumentMetadata(
            doc_id=doc_id,
            nis_id=nis_id,
            file_name=file_name,
            document_type=document_type,
            document_class=document_class,
            bucket_name=bucket_name,
            object_path=object_path,
            content_type=content_type,
            file_size_bytes=file_size_bytes,
            uploaded_by=uploaded_by,
            correlation_id=correlation_id,
            salesforce_record_id=salesforce_record_id,
            salesforce_object_type=salesforce_object_type,
            description=description,
            expiry_date=expiry_date,
            etag=etag,
            version_id=version_id,
        )
        self._db.add(record)
        self._db.commit()
        self._db.refresh(record)
        return record

    def soft_delete(self, doc_id: str) -> Optional[DocumentMetadata]:
        """
        Mark a document as deleted without removing the row or the MinIO object.
        Returns the updated record, or None if doc_id does not exist.
        """
        record = self.get_by_doc_id(doc_id, include_deleted=False)
        if record is None:
            return None
        record.is_deleted = True
        record.deleted_at = datetime.now(timezone.utc)
        self._db.commit()
        self._db.refresh(record)
        return record

    # ── Reads ─────────────────────────────────────────────────────────────────

    def get_by_doc_id(
        self,
        doc_id:          str,
        include_deleted: bool = False,
    ) -> Optional[DocumentMetadata]:
        """Return a single document by its doc_id, or None."""
        q = self._db.query(DocumentMetadata).filter(
            DocumentMetadata.doc_id == doc_id
        )
        if not include_deleted:
            q = q.filter(DocumentMetadata.is_deleted == False)  # noqa: E712
        return q.first()

    def get_by_nis_id(
        self,
        nis_id:          str,
        include_deleted: bool  = False,
        skip:            int   = 0,
        limit:           int   = 200,
    ) -> List[DocumentMetadata]:
        """
        Return all documents belonging to a NIS ID, ordered newest-first.
        Active (non-deleted) documents only by default.
        """
        q = self._db.query(DocumentMetadata).filter(
            DocumentMetadata.nis_id == nis_id
        )
        if not include_deleted:
            q = q.filter(DocumentMetadata.is_deleted == False)  # noqa: E712
        return (
            q.order_by(DocumentMetadata.uploaded_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )

    def count_by_nis_id(self, nis_id: str) -> int:
        """Return the count of active documents for a NIS ID (used for document_count field)."""
        return (
            self._db.query(DocumentMetadata)
            .filter(
                DocumentMetadata.nis_id    == nis_id,
                DocumentMetadata.is_deleted == False,  # noqa: E712
            )
            .count()
        )

    def find_active_duplicate(
        self,
        nis_id:        str,
        document_type: str,
        file_name:     str,
    ) -> Optional[DocumentMetadata]:
        """
        Return the first active (non-deleted) document whose nis_id, document_type,
        and file_name all match.  Used by the upload endpoint for duplicate detection.
        Returns None if no match is found.
        """
        return (
            self._db.query(DocumentMetadata)
            .filter(
                DocumentMetadata.nis_id        == nis_id,
                DocumentMetadata.document_type == document_type,
                DocumentMetadata.file_name     == file_name,
                DocumentMetadata.is_deleted    == False,  # noqa: E712
            )
            .first()
        )
